<%--
 % Copyright 2011 - Kementerian Pendidikan Nasional - Dit.PSMP
 %
 % Author(s):
 % + x10c-Lab
 %   - agus sugianto (agus.delonge@gmail.com)
--%>

<%@ page import="java.sql.*" %>
<%@ page import="java.io.*" %>
<%
String	kd_tahun_ajaran		= (String) session.getAttribute("kd.tahun_pelajaran");
String	npsn				= request.getParameter("npsn");
String	id_propinsi			= request.getParameter("id_propinsi");
String	id_kabupaten		= request.getParameter("id_kabupaten");
String	id_kecamatan		= request.getParameter("id_kecamatan");

String 	q	= "";
int		iLf	= 10;
char	cLf	= (char)iLf;

File		outputFile	= new File("C:\\03 - " + kd_tahun_ajaran + "_" + npsn + "_A_SEKOLAH_SISWA_01.XML");
outputFile.createNewFile();
FileWriter	outFile		= new FileWriter(outputFile);

outFile.write("<?xml version='1.0' encoding='UTF-8'?>" + cLf);
try{
	Connection	db_con	= (Connection) session.getAttribute("db.con");
	if (db_con == null || (db_con != null && db_con.isClosed())) {
		response.sendRedirect(request.getContextPath());
		return;
	}

	Statement	db_stmt = db_con.createStatement();
	
	q	=" SELECT	KD_TAHUN_AJARAN"
		+" ,		ID_PROPINSI"
		+" ,		ID_KABUPATEN"
		+" ,		ID_KECAMATAN"
		+" ,		NPSN"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 12 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_01_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 12 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_01_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 12 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_02_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 12 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_02_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_03_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_03_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_04_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_04_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_05_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_05_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_06_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_06_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_07_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_BAR_07_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '1'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_01_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '1'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_01_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '2'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_02_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '2'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_02_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '3'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_03_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '3'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_03_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '4'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_04_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '4'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_04_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '5'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_05_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '5'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_05_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '6'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_06_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '6'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_01_06_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '1'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_01_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '1'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_01_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '2'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_02_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '2'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_02_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '3'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_03_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '3'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_03_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '4'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_04_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '4'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_04_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '5'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_05_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '5'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_05_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '6'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_06_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '6'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_02_06_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '1'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_01_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '1'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_01_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '2'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_02_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '2'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_02_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '3'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_03_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '3'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_03_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '4'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_04_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '4'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_04_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '5'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_05_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '5'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_05_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '6'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_06_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_AGAMA 			= '6'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS AGM_03_06_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_01_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '01'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_01_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_02_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '02'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_02_P"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '1'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_03_L"
		+" ,		("
		+" 		SELECT	COUNT(*)"
		+" 		FROM	t_siswa_tingkat"
		+" 		,		t_siswa"
		+" 		WHERE	t_siswa_tingkat.ID_SISWA			= t_siswa.ID_SISWA"
		+" 		AND		t_siswa.STATUS_SISWA				NOT IN ('1','4','6')"
		+" 		AND		t_siswa_tingkat.KD_TINGKAT_KELAS 	= '03'"
		+" 		AND		t_siswa_tingkat.KD_JENIS_KELAMIN 	= '2'"
		+" 		AND		t_siswa_tingkat.KD_TAHUN_AJARAN 	= '" + kd_tahun_ajaran + "'"
		+" 		) AS SIS_03_P"
		+" FROM	t_sekolah_identitas"
		+" WHERE	KD_TAHUN_AJARAN	= '" + kd_tahun_ajaran + "'";
	
	ResultSet	rs	= db_stmt.executeQuery(q);

	outFile.write("<DATA>" + cLf);
	
	while (rs.next()){
		outFile.write("<DATA_ROW>" + cLf);
		outFile.write("<KD_TAHUN_AJARAN>" + rs.getString("KD_TAHUN_AJARAN") + "</KD_TAHUN_AJARAN>" + cLf);
		outFile.write("<ID_PROPINSI>" + rs.getString("ID_PROPINSI") + "</ID_PROPINSI>" + cLf);
		outFile.write("<ID_KABUPATEN>" + rs.getString("ID_KABUPATEN") + "</ID_KABUPATEN>" + cLf);
		outFile.write("<ID_KECAMATAN>" + rs.getString("ID_KECAMATAN") + "</ID_KECAMATAN>" + cLf);
		outFile.write("<NPSN>" + rs.getString("NPSN") + "</NPSN>" + cLf);
		outFile.write("<SIS_BAR_01_L>" + rs.getString("SIS_BAR_01_L") + "</SIS_BAR_01_L>" + cLf);
		outFile.write("<SIS_BAR_01_P>" + rs.getString("SIS_BAR_01_P") + "</SIS_BAR_01_P>" + cLf);
		outFile.write("<SIS_BAR_02_L>" + rs.getString("SIS_BAR_02_L") + "</SIS_BAR_02_L>" + cLf);
		outFile.write("<SIS_BAR_02_P>" + rs.getString("SIS_BAR_02_P") + "</SIS_BAR_02_P>" + cLf);
		outFile.write("<SIS_BAR_03_L>" + rs.getString("SIS_BAR_03_L") + "</SIS_BAR_03_L>" + cLf);
		outFile.write("<SIS_BAR_03_P>" + rs.getString("SIS_BAR_03_P") + "</SIS_BAR_03_P>" + cLf);
		outFile.write("<SIS_BAR_04_L>" + rs.getString("SIS_BAR_04_L") + "</SIS_BAR_04_L>" + cLf);
		outFile.write("<SIS_BAR_04_P>" + rs.getString("SIS_BAR_04_P") + "</SIS_BAR_04_P>" + cLf);
		outFile.write("<SIS_BAR_05_L>" + rs.getString("SIS_BAR_05_L") + "</SIS_BAR_05_L>" + cLf);
		outFile.write("<SIS_BAR_05_P>" + rs.getString("SIS_BAR_05_P") + "</SIS_BAR_05_P>" + cLf);
		outFile.write("<SIS_BAR_06_L>" + rs.getString("SIS_BAR_06_L") + "</SIS_BAR_06_L>" + cLf);
		outFile.write("<SIS_BAR_06_P>" + rs.getString("SIS_BAR_06_P") + "</SIS_BAR_06_P>" + cLf);
		outFile.write("<SIS_BAR_07_L>" + rs.getString("SIS_BAR_07_L") + "</SIS_BAR_07_L>" + cLf);
		outFile.write("<SIS_BAR_07_P>" + rs.getString("SIS_BAR_07_P") + "</SIS_BAR_07_P>" + cLf);
		outFile.write("<AGM_01_01_L>" + rs.getString("AGM_01_01_L") + "</AGM_01_01_L>" + cLf);
		outFile.write("<AGM_01_01_P>" + rs.getString("AGM_01_01_P") + "</AGM_01_01_P>" + cLf);
		outFile.write("<AGM_01_02_L>" + rs.getString("AGM_01_02_L") + "</AGM_01_02_L>" + cLf);
		outFile.write("<AGM_01_02_P>" + rs.getString("AGM_01_02_P") + "</AGM_01_02_P>" + cLf);
		outFile.write("<AGM_01_03_L>" + rs.getString("AGM_01_03_L") + "</AGM_01_03_L>" + cLf);
		outFile.write("<AGM_01_03_P>" + rs.getString("AGM_01_03_P") + "</AGM_01_03_P>" + cLf);
		outFile.write("<AGM_01_04_L>" + rs.getString("AGM_01_04_L") + "</AGM_01_04_L>" + cLf);
		outFile.write("<AGM_01_04_P>" + rs.getString("AGM_01_04_P") + "</AGM_01_04_P>" + cLf);
		outFile.write("<AGM_01_05_L>" + rs.getString("AGM_01_05_L") + "</AGM_01_05_L>" + cLf);
		outFile.write("<AGM_01_05_P>" + rs.getString("AGM_01_05_P") + "</AGM_01_05_P>" + cLf);
		outFile.write("<AGM_01_06_L>" + rs.getString("AGM_01_06_L") + "</AGM_01_06_L>" + cLf);
		outFile.write("<AGM_01_06_P>" + rs.getString("AGM_01_06_P") + "</AGM_01_06_P>" + cLf);
		outFile.write("<AGM_02_01_L>" + rs.getString("AGM_02_01_L") + "</AGM_02_01_L>" + cLf);
		outFile.write("<AGM_02_01_P>" + rs.getString("AGM_02_01_P") + "</AGM_02_01_P>" + cLf);
		outFile.write("<AGM_02_02_L>" + rs.getString("AGM_02_02_L") + "</AGM_02_02_L>" + cLf);
		outFile.write("<AGM_02_02_P>" + rs.getString("AGM_02_02_P") + "</AGM_02_02_P>" + cLf);
		outFile.write("<AGM_02_03_L>" + rs.getString("AGM_02_03_L") + "</AGM_02_03_L>" + cLf);
		outFile.write("<AGM_02_03_P>" + rs.getString("AGM_02_03_P") + "</AGM_02_03_P>" + cLf);
		outFile.write("<AGM_02_04_L>" + rs.getString("AGM_02_04_L") + "</AGM_02_04_L>" + cLf);
		outFile.write("<AGM_02_04_P>" + rs.getString("AGM_02_04_P") + "</AGM_02_04_P>" + cLf);
		outFile.write("<AGM_02_05_L>" + rs.getString("AGM_02_05_L") + "</AGM_02_05_L>" + cLf);
		outFile.write("<AGM_02_05_P>" + rs.getString("AGM_02_05_P") + "</AGM_02_05_P>" + cLf);
		outFile.write("<AGM_02_06_L>" + rs.getString("AGM_02_06_L") + "</AGM_02_06_L>" + cLf);
		outFile.write("<AGM_02_06_P>" + rs.getString("AGM_02_06_P") + "</AGM_02_06_P>" + cLf);
		outFile.write("<AGM_03_01_L>" + rs.getString("AGM_03_01_L") + "</AGM_03_01_L>" + cLf);
		outFile.write("<AGM_03_01_P>" + rs.getString("AGM_03_01_P") + "</AGM_03_01_P>" + cLf);
		outFile.write("<AGM_03_02_L>" + rs.getString("AGM_03_02_L") + "</AGM_03_02_L>" + cLf);
		outFile.write("<AGM_03_02_P>" + rs.getString("AGM_03_02_P") + "</AGM_03_02_P>" + cLf);
		outFile.write("<AGM_03_03_L>" + rs.getString("AGM_03_03_L") + "</AGM_03_03_L>" + cLf);
		outFile.write("<AGM_03_03_P>" + rs.getString("AGM_03_03_P") + "</AGM_03_03_P>" + cLf);
		outFile.write("<AGM_03_04_L>" + rs.getString("AGM_03_04_L") + "</AGM_03_04_L>" + cLf);
		outFile.write("<AGM_03_04_P>" + rs.getString("AGM_03_04_P") + "</AGM_03_04_P>" + cLf);
		outFile.write("<AGM_03_05_L>" + rs.getString("AGM_03_05_L") + "</AGM_03_05_L>" + cLf);
		outFile.write("<AGM_03_05_P>" + rs.getString("AGM_03_05_P") + "</AGM_03_05_P>" + cLf);
		outFile.write("<AGM_03_06_L>" + rs.getString("AGM_03_06_L") + "</AGM_03_06_L>" + cLf);
		outFile.write("<AGM_03_06_P>" + rs.getString("AGM_03_06_P") + "</AGM_03_06_P>" + cLf);
		outFile.write("<SIS_01_L>" + rs.getString("SIS_01_L") + "</SIS_01_L>" + cLf);
		outFile.write("<SIS_01_P>" + rs.getString("SIS_01_P") + "</SIS_01_P>" + cLf);
		outFile.write("<SIS_02_L>" + rs.getString("SIS_02_L") + "</SIS_02_L>" + cLf);
		outFile.write("<SIS_02_P>" + rs.getString("SIS_02_P") + "</SIS_02_P>" + cLf);
		outFile.write("<SIS_03_L>" + rs.getString("SIS_03_L") + "</SIS_03_L>" + cLf);
		outFile.write("<SIS_03_P>" + rs.getString("SIS_03_P") + "</SIS_03_P>" + cLf);
		outFile.write("</DATA_ROW>" + cLf);
	}	
	
	outFile.write("</DATA>" + cLf);
	
	rs.close();
	outFile.close();
}catch (Exception e){
	out.print("{success:false,info:'"+ e.toString().replace("'","\\'") +"'}");
	outFile.close();
}
%>
