<%--
 % Copyright 2011 - Kementerian Pendidikan Nasional - Dit.PSMP
 %
 % Author(s):
 % + x10c-Lab
 %   - agus sugianto (agus.delonge@gmail.com)
--%>

<%@ page import="java.sql.*" %>
<%@ page import="java.io.*" %>
<%
String	kd_tahun_ajaran		= (String) session.getAttribute("kd.tahun_pelajaran");
String	npsn				= request.getParameter("npsn");
String	id_propinsi			= request.getParameter("id_propinsi");
String	id_kabupaten		= request.getParameter("id_kabupaten");
String	id_kecamatan		= request.getParameter("id_kecamatan");

String 	q	= "";
int		iLf	= 10;
char	cLf	= (char)iLf;

File		outputFile	= new File("C:\\04 - " + kd_tahun_ajaran + "_" + npsn + "_A_SEKOLAH_SISWA_02.XML");
outputFile.createNewFile();
FileWriter	outFile		= new FileWriter(outputFile);

outFile.write("<?xml version='1.0' encoding='UTF-8'?>" + cLf);
try{
	Connection	db_con	= (Connection) session.getAttribute("db.con");
	if (db_con == null || (db_con != null && db_con.isClosed())) {
		response.sendRedirect(request.getContextPath());
		return;
	}

	Statement	db_stmt = db_con.createStatement();
	
	q	=" SELECT	KD_TAHUN_AJARAN"
		+" ,		ID_PROPINSI"
		+" ,		ID_KABUPATEN"
		+" ,		ID_KECAMATAN"
		+" ,		NPSN"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_01_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_01_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_02_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_02_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_03_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_03_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_04_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_04_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_05_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_05_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 17 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_06_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 17 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_06_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 18 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_07_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 18 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_07_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 19 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_08_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 19 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_08_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 20 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_09_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 20 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_09_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_10_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_10_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_11_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '01' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_01_11_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_01_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_01_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_02_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_02_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_03_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_03_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_04_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_04_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_05_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_05_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 17 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_06_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 17 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_06_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 18 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_07_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 18 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_07_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 19 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_08_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 19 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_08_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 20 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_09_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 20 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_09_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_10_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_10_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_11_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '02' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_02_11_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_01_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR < 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_01_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_02_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 13 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_02_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_03_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 14 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_03_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_04_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 15 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_04_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_05_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 16 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_05_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 17 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_06_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 17 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_06_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 18 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_07_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 18 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_07_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 19 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_08_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 19 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_08_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 20 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_09_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 20 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_09_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_10_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR = 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_10_P"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '1',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_11_L"
		+" ,		("
		+" 		SELECT		IFNULL(SUM(IF(v_siswa_umur.UMUR > 21 AND t_siswa_tingkat.KD_TINGKAT_KELAS = '03' AND v_siswa_umur.KD_JNS_KELAMIN = '2',1,0)),0)"
		+" 		FROM		t_siswa_tingkat"
		+" 		LEFT JOIN	v_siswa_umur	ON (t_siswa_tingkat.ID_SISWA = v_siswa_umur.ID_SISWA)"
		+" 		LEFT JOIN	t_siswa			ON (t_siswa_tingkat.ID_SISWA = t_siswa.ID_SISWA)"
		+" 		WHERE 		t_siswa.STATUS_SISWA			NOT IN ('1','4','6')"
		+" 		AND			t_siswa_tingkat.KD_TAHUN_AJARAN = '" + kd_tahun_ajaran + "'"
		+" 		) AS UMR_03_11_P"
		+" FROM	t_sekolah_identitas"
		+" WHERE	KD_TAHUN_AJARAN	= '" + kd_tahun_ajaran + "'";
	
	ResultSet	rs	= db_stmt.executeQuery(q);

	outFile.write("<DATA>" + cLf);
	
	while (rs.next()){
		outFile.write("<DATA_ROW>" + cLf);
		outFile.write("<KD_TAHUN_AJARAN>" + rs.getString("KD_TAHUN_AJARAN") + "</KD_TAHUN_AJARAN>" + cLf);
		outFile.write("<ID_PROPINSI>" + rs.getString("ID_PROPINSI") + "</ID_PROPINSI>" + cLf);
		outFile.write("<ID_KABUPATEN>" + rs.getString("ID_KABUPATEN") + "</ID_KABUPATEN>" + cLf);
		outFile.write("<ID_KECAMATAN>" + rs.getString("ID_KECAMATAN") + "</ID_KECAMATAN>" + cLf);
		outFile.write("<NPSN>" + rs.getString("NPSN") + "</NPSN>" + cLf);
		outFile.write("<UMR_01_01_L>" + rs.getString("UMR_01_01_L") + "</UMR_01_01_L>" + cLf);
		outFile.write("<UMR_01_01_P>" + rs.getString("UMR_01_01_P") + "</UMR_01_01_P>" + cLf);
		outFile.write("<UMR_01_02_L>" + rs.getString("UMR_01_02_L") + "</UMR_01_02_L>" + cLf);
		outFile.write("<UMR_01_02_P>" + rs.getString("UMR_01_02_P") + "</UMR_01_02_P>" + cLf);
		outFile.write("<UMR_01_03_L>" + rs.getString("UMR_01_03_L") + "</UMR_01_03_L>" + cLf);
		outFile.write("<UMR_01_03_P>" + rs.getString("UMR_01_03_P") + "</UMR_01_03_P>" + cLf);
		outFile.write("<UMR_01_04_L>" + rs.getString("UMR_01_04_L") + "</UMR_01_04_L>" + cLf);
		outFile.write("<UMR_01_04_P>" + rs.getString("UMR_01_04_P") + "</UMR_01_04_P>" + cLf);
		outFile.write("<UMR_01_05_L>" + rs.getString("UMR_01_05_L") + "</UMR_01_05_L>" + cLf);
		outFile.write("<UMR_01_05_P>" + rs.getString("UMR_01_05_P") + "</UMR_01_05_P>" + cLf);
		outFile.write("<UMR_01_06_L>" + rs.getString("UMR_01_06_L") + "</UMR_01_06_L>" + cLf);
		outFile.write("<UMR_01_06_P>" + rs.getString("UMR_01_06_P") + "</UMR_01_06_P>" + cLf);
		outFile.write("<UMR_01_07_L>" + rs.getString("UMR_01_07_L") + "</UMR_01_07_L>" + cLf);
		outFile.write("<UMR_01_07_P>" + rs.getString("UMR_01_07_P") + "</UMR_01_07_P>" + cLf);
		outFile.write("<UMR_01_08_L>" + rs.getString("UMR_01_08_L") + "</UMR_01_08_L>" + cLf);
		outFile.write("<UMR_01_08_P>" + rs.getString("UMR_01_08_P") + "</UMR_01_08_P>" + cLf);
		outFile.write("<UMR_01_09_L>" + rs.getString("UMR_01_09_L") + "</UMR_01_09_L>" + cLf);
		outFile.write("<UMR_01_09_P>" + rs.getString("UMR_01_09_P") + "</UMR_01_09_P>" + cLf);
		outFile.write("<UMR_01_10_L>" + rs.getString("UMR_01_10_L") + "</UMR_01_10_L>" + cLf);
		outFile.write("<UMR_01_10_P>" + rs.getString("UMR_01_10_P") + "</UMR_01_10_P>" + cLf);
		outFile.write("<UMR_01_11_L>" + rs.getString("UMR_01_11_L") + "</UMR_01_11_L>" + cLf);
		outFile.write("<UMR_01_11_P>" + rs.getString("UMR_01_11_P") + "</UMR_01_11_P>" + cLf);
		outFile.write("<UMR_02_01_L>" + rs.getString("UMR_02_01_L") + "</UMR_02_01_L>" + cLf);
		outFile.write("<UMR_02_01_P>" + rs.getString("UMR_02_01_P") + "</UMR_02_01_P>" + cLf);
		outFile.write("<UMR_02_02_L>" + rs.getString("UMR_02_02_L") + "</UMR_02_02_L>" + cLf);
		outFile.write("<UMR_02_02_P>" + rs.getString("UMR_02_02_P") + "</UMR_02_02_P>" + cLf);
		outFile.write("<UMR_02_03_L>" + rs.getString("UMR_02_03_L") + "</UMR_02_03_L>" + cLf);
		outFile.write("<UMR_02_03_P>" + rs.getString("UMR_02_03_P") + "</UMR_02_03_P>" + cLf);
		outFile.write("<UMR_02_04_L>" + rs.getString("UMR_02_04_L") + "</UMR_02_04_L>" + cLf);
		outFile.write("<UMR_02_04_P>" + rs.getString("UMR_02_04_P") + "</UMR_02_04_P>" + cLf);
		outFile.write("<UMR_02_05_L>" + rs.getString("UMR_02_05_L") + "</UMR_02_05_L>" + cLf);
		outFile.write("<UMR_02_05_P>" + rs.getString("UMR_02_05_P") + "</UMR_02_05_P>" + cLf);
		outFile.write("<UMR_02_06_L>" + rs.getString("UMR_02_06_L") + "</UMR_02_06_L>" + cLf);
		outFile.write("<UMR_02_06_P>" + rs.getString("UMR_02_06_P") + "</UMR_02_06_P>" + cLf);
		outFile.write("<UMR_02_07_L>" + rs.getString("UMR_02_07_L") + "</UMR_02_07_L>" + cLf);
		outFile.write("<UMR_02_07_P>" + rs.getString("UMR_02_07_P") + "</UMR_02_07_P>" + cLf);
		outFile.write("<UMR_02_08_L>" + rs.getString("UMR_02_08_L") + "</UMR_02_08_L>" + cLf);
		outFile.write("<UMR_02_08_P>" + rs.getString("UMR_02_08_P") + "</UMR_02_08_P>" + cLf);
		outFile.write("<UMR_02_09_L>" + rs.getString("UMR_02_09_L") + "</UMR_02_09_L>" + cLf);
		outFile.write("<UMR_02_09_P>" + rs.getString("UMR_02_09_P") + "</UMR_02_09_P>" + cLf);
		outFile.write("<UMR_02_10_L>" + rs.getString("UMR_02_10_L") + "</UMR_02_10_L>" + cLf);
		outFile.write("<UMR_02_10_P>" + rs.getString("UMR_02_10_P") + "</UMR_02_10_P>" + cLf);
		outFile.write("<UMR_02_11_L>" + rs.getString("UMR_02_11_L") + "</UMR_02_11_L>" + cLf);
		outFile.write("<UMR_02_11_P>" + rs.getString("UMR_02_11_P") + "</UMR_02_11_P>" + cLf);
		outFile.write("<UMR_03_01_L>" + rs.getString("UMR_03_01_L") + "</UMR_03_01_L>" + cLf);
		outFile.write("<UMR_03_01_P>" + rs.getString("UMR_03_01_P") + "</UMR_03_01_P>" + cLf);
		outFile.write("<UMR_03_02_L>" + rs.getString("UMR_03_02_L") + "</UMR_03_02_L>" + cLf);
		outFile.write("<UMR_03_02_P>" + rs.getString("UMR_03_02_P") + "</UMR_03_02_P>" + cLf);
		outFile.write("<UMR_03_03_L>" + rs.getString("UMR_03_03_L") + "</UMR_03_03_L>" + cLf);
		outFile.write("<UMR_03_03_P>" + rs.getString("UMR_03_03_P") + "</UMR_03_03_P>" + cLf);
		outFile.write("<UMR_03_04_L>" + rs.getString("UMR_03_04_L") + "</UMR_03_04_L>" + cLf);
		outFile.write("<UMR_03_04_P>" + rs.getString("UMR_03_04_P") + "</UMR_03_04_P>" + cLf);
		outFile.write("<UMR_03_05_L>" + rs.getString("UMR_03_05_L") + "</UMR_03_05_L>" + cLf);
		outFile.write("<UMR_03_05_P>" + rs.getString("UMR_03_05_P") + "</UMR_03_05_P>" + cLf);
		outFile.write("<UMR_03_06_L>" + rs.getString("UMR_03_06_L") + "</UMR_03_06_L>" + cLf);
		outFile.write("<UMR_03_06_P>" + rs.getString("UMR_03_06_P") + "</UMR_03_06_P>" + cLf);
		outFile.write("<UMR_03_07_L>" + rs.getString("UMR_03_07_L") + "</UMR_03_07_L>" + cLf);
		outFile.write("<UMR_03_07_P>" + rs.getString("UMR_03_07_P") + "</UMR_03_07_P>" + cLf);
		outFile.write("<UMR_03_08_L>" + rs.getString("UMR_03_08_L") + "</UMR_03_08_L>" + cLf);
		outFile.write("<UMR_03_08_P>" + rs.getString("UMR_03_08_P") + "</UMR_03_08_P>" + cLf);
		outFile.write("<UMR_03_09_L>" + rs.getString("UMR_03_09_L") + "</UMR_03_09_L>" + cLf);
		outFile.write("<UMR_03_09_P>" + rs.getString("UMR_03_09_P") + "</UMR_03_09_P>" + cLf);
		outFile.write("<UMR_03_10_L>" + rs.getString("UMR_03_10_L") + "</UMR_03_10_L>" + cLf);
		outFile.write("<UMR_03_10_P>" + rs.getString("UMR_03_10_P") + "</UMR_03_10_P>" + cLf);
		outFile.write("<UMR_03_11_L>" + rs.getString("UMR_03_11_L") + "</UMR_03_11_L>" + cLf);
		outFile.write("<UMR_03_11_P>" + rs.getString("UMR_03_11_P") + "</UMR_03_11_P>" + cLf);
		outFile.write("</DATA_ROW>" + cLf);
	}	
	
	outFile.write("</DATA>" + cLf);
	
	rs.close();
	outFile.close();
}catch (Exception e){
	out.print("{success:false,info:'"+ e.toString().replace("'","\\'") +"'}");
	outFile.close();
}
%>
