/* V_KUR_KURIKULUM */
DROP VIEW IF EXISTS pas_smp.V_KUR_KURIKULUM;

CREATE VIEW pas_smp.V_KUR_KURIKULUM
AS
SELECT
    MAX(A.KD_KURIKULUM)             AS KD_THN_BERLAKU
,   B.NM_KURIKULUM                  AS NM_TAHUN_AJARAN
,   A.KD_TINGKAT_KELAS              AS KD_TINGKAT_KELAS
,   C.NM_TINGKAT_KELAS              AS NM_TINGKAT_KELAS
,   A.KD_PERIODE_BELAJAR            AS KD_PERIODE_BELAJAR
,   D.NM_PERIODE_BELAJAR            AS NM_PERIODE_BELAJAR
,   A.KD_MATA_PELAJARAN_DIAJARKAN   AS KD_MATA_PELAJARAN_DIAJARKAN
,   E.NM_MATA_PELAJARAN_DIAJARKAN   AS NM_MATA_PELAJARAN_DIAJARKAN
FROM
    (((( T_KUR_KURIKULUM            AS A 
    JOIN R_KURIKULUM                AS B) 
    JOIN R_TINGKAT_KELAS            AS C)
    JOIN R_PERIODE_BELAJAR          AS D)
    JOIN R_MATA_PELAJARAN_DIAJARKAN AS E)
WHERE
    (
        (B.KD_KURIKULUM                 = A.KD_KURIKULUM)
    AND (C.KD_TINGKAT_KELAS             = A.KD_TINGKAT_KELAS)
    AND (D.KD_PERIODE_BELAJAR           = A.KD_PERIODE_BELAJAR)
    AND (E.KD_MATA_PELAJARAN_DIAJARKAN  = A.KD_MATA_PELAJARAN_DIAJARKAN)
    )
GROUP BY
    B.NM_KURIKULUM
,   A.KD_TINGKAT_KELAS
,   C.NM_TINGKAT_KELAS
,   A.KD_PERIODE_BELAJAR
,   D.NM_PERIODE_BELAJAR
,   A.KD_MATA_PELAJARAN_DIAJARKAN
,   E.NM_MATA_PELAJARAN_DIAJARKAN;

/* V_KUR_KURIKULUM_KELAS */
DROP VIEW IF EXISTS pas_smp.V_KUR_KURIKULUM_KELAS;

CREATE VIEW pas_smp.V_KUR_KURIKULUM_KELAS
AS
SELECT  DISTINCT
	KD_KURIKULUM
,	KD_TINGKAT_KELAS
FROM    
	T_KUR_KURIKULUM
ORDER BY 
	KD_KURIKULUM, KD_TINGKAT_KELAS;

/* V_PEGAWAI_JABATAN_AWAL_AKHIR */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_JABATAN_AWAL_AKHIR;

CREATE VIEW pas_smp.V_PEGAWAI_JABATAN_AWAL_AKHIR
AS 
SELECT
	ID_PEGAWAI AS ID_PEGAWAI
,	MIN(NO_URUT) AS MIN_NO_URUT
,	MAX(NO_URUT) AS MAX_NO_URUT
FROM
	T_PEGAWAI_RWYT_JABATAN
GROUP BY 
	ID_PEGAWAI;

/* V_PEGAWAI_TGL_SK_JABATAN */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_TGL_SK_JABATAN;

CREATE VIEW pas_smp.V_PEGAWAI_TGL_SK_JABATAN
AS
SELECT
	A.ID_PEGAWAI				AS ID_PEGAWAI
,	B.KD_JENIS_PEGAWAI			AS KD_JENIS_PEGAWAI
,	B.NO_SK						AS NO_SK
,	B.TANGGAL_SK				AS TGL_SK
,	(
		SELECT	MAX(F.TMT_SK)
		FROM	T_PEGAWAI_RWYT_JABATAN AS F
		WHERE	F.ID_PEGAWAI = A.ID_PEGAWAI
	) AS TMT_SK
,	D.NO_SK						AS NO_SK_AWAL
,	D.TANGGAL_SK				AS TGL_SK_AWAL
,  	(
		SELECT	MIN(G.TMT_SK)
		FROM 	T_PEGAWAI_RWYT_JABATAN AS G
		WHERE	G.ID_PEGAWAI = A.ID_PEGAWAI
	) AS TMT_SK_AWAL
,	YEAR(D.TMT_SK)				AS THN_JD_GURU
,	A.KD_JENIS_KETENAGAAN		AS KD_JENIS_KETENAGAAN
,	A.TANGGAL_LAHIR				AS TGL_LAHIR
,	D.KD_JABATAN_PEGAWAI     	AS KD_JABATAN_PEGAWAI
,	A.NM_PEGAWAI             	AS NM_PEGAWAI
,	A.KOTA_LAHIR             	AS KOTA_LAHIR
,	A.KD_JENIS_KELAMIN       	AS KD_JNS_KELAMIN
,	D.KD_TENAGA_ADMINISTRASI 	AS KD_TENAGA_ADMINISTRASI
FROM
	(((( T_PEGAWAI 						AS A
	JOIN T_PEGAWAI_RWYT_JABATAN 		AS B)
	JOIN V_PEGAWAI_JABATAN_AWAL_AKHIR	AS C)
	JOIN T_PEGAWAI_RWYT_JABATAN 		AS D)
	JOIN V_PEGAWAI_JABATAN_AWAL_AKHIR 	AS E)
WHERE 	A.ID_PEGAWAI	= B.ID_PEGAWAI
AND 	C.ID_PEGAWAI	= B.ID_PEGAWAI
AND 	C.MAX_NO_URUT	= B.NO_URUT
AND 	D.ID_PEGAWAI 	= A.ID_PEGAWAI
AND 	E.ID_PEGAWAI 	= D.ID_PEGAWAI
AND 	E.MIN_NO_URUT 	= D.NO_URUT;

/* V_PEGAWAI_USIA_MASAKERJA */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_USIA_MASAKERJA;

CREATE VIEW pas_smp.V_PEGAWAI_USIA_MASAKERJA
AS
SELECT
	C.ID_PEGAWAI				AS ID_PEGAWAI
,	C.KD_JENIS_KETENAGAAN		AS KD_JENIS_KETENAGAAN
,	A.KD_TAHUN_AJARAN        	AS KD_TAHUN_AJARAN
,	C.TGL_SK                 	AS TGL_SK
,	C.TMT_SK                 	AS TMT_SK
,	C.KD_JENIS_PEGAWAI       	AS KD_JENIS_PEGAWAI
,	YEAR(C.THN_JD_GURU)      	AS THN_JADI_GURU
,	C.TGL_LAHIR              	AS TGL_LAHIR
,	(CAST(LEFT(B.NM_TAHUN_AJARAN,4) AS DECIMAL) - YEAR(C.TGL_LAHIR))	AS UMUR
,	(CAST(LEFT(B.NM_TAHUN_AJARAN,4) AS DECIMAL) - YEAR(C.TMT_SK)) 		AS MS_KRJ_SK
,	(CAST(LEFT(B.NM_TAHUN_AJARAN,4) AS DECIMAL) - YEAR(C.TMT_SK_AWAL)) 	AS MS_KRJ_AWAL
,	C.KD_JABATAN_PEGAWAI     	AS KD_JABATAN_PEGAWAI
,	C.NM_PEGAWAI             	AS NM_PEGAWAI
,	C.KOTA_LAHIR             	AS KOTA_LAHIR
,	C.KD_JNS_KELAMIN         	AS KD_JNS_KELAMIN
,	C.KD_TENAGA_ADMINISTRASI 	AS KD_TENAGA_ADMINISTRASI
FROM 
	(( T_SEKOLAH_IDENTITAS 			AS A
	JOIN R_TAHUN_AJARAN 			AS B)
	JOIN V_PEGAWAI_TGL_SK_JABATAN 	AS C)
WHERE 	B.KD_TAHUN_AJARAN = A.KD_TAHUN_AJARAN;

/* V_PEGAWAI_PANGKAT_AKHIR */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_PANGKAT_AKHIR;

CREATE VIEW pas_smp.V_PEGAWAI_PANGKAT_AKHIR
AS
SELECT
	ID_PEGAWAI 		AS ID_PEGAWAI
,	MAX(NO_URUT) 	AS NO_URUT
FROM 	
	T_PEGAWAI_RWYT_PANGKAT
GROUP BY 
	ID_PEGAWAI;

/* V_PEGAWAI_TGL_SK_PANGKAT */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_TGL_SK_PANGKAT;

CREATE VIEW pas_smp.V_PEGAWAI_TGL_SK_PANGKAT
AS
SELECT
	A.ID_PEGAWAI			AS ID_PEGAWAI
,	A.KD_JENIS_KELAMIN    	AS KD_JNS_KELAMIN
,	B.NO_URUT             	AS NO_URUT
,	B.NO_SK               	AS NO_SK
,	B.TANGGAL_SK          	AS TGL_SK
,	B.TMT_SK              	AS TMT_SK
,	B.KD_STATUS_PEGAWAI   	AS KD_STATUS_PEGAWAI
,	B.KD_PANGKAT          	AS KD_PANGKAT
,	B.KETERANGAN          	AS KETERANGAN
,	A.KD_JENIS_KETENAGAAN 	AS KD_JENIS_KETENAGAAN
FROM 
	(( t_pegawai 					AS A
	JOIN t_pegawai_rwyt_pangkat 	AS B)
	JOIN v_pegawai_pangkat_akhir	AS C)
WHERE 	C.ID_PEGAWAI 	= A.ID_PEGAWAI
AND 	B.ID_PEGAWAI 	= C.ID_PEGAWAI
AND 	B.NO_URUT 		= C.NO_URUT;

/* V_PEGAWAI_JML_KELUARGA */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_JML_KELUARGA;

CREATE VIEW pas_smp.V_PEGAWAI_JML_KELUARGA
AS
SELECT
	ID_PEGAWAI AS ID_PEGAWAI
,	SUM(IF(((KD_HUB_KELUARGA = 'I') OR (KD_HUB_KELUARGA = 'S')),1,0)) AS IST
,	SUM(IF(((KD_HUB_KELUARGA = 'K') OR (KD_HUB_KELUARGA = 'T')),1,0)) AS ANK
FROM
	T_PEGAWAI_KELUARGA
GROUP BY 
	ID_PEGAWAI;

/* V_PEGAWAI_DIDIK_MAX */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_DIDIK_MAX;

CREATE VIEW pas_smp.V_PEGAWAI_DIDIK_MAX
AS
SELECT
	ID_PEGAWAI		AS ID_PEGAWAI
,	MAX(NO_URUT) 	AS URUT
FROM
	T_PEGAWAI_DIDIK_FORMAL
GROUP BY
	ID_PEGAWAI;

/* V_PEGAWAI_LULUS_PENDIDIKAN */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_LULUS_PENDIDIKAN;

CREATE VIEW pas_smp.V_PEGAWAI_LULUS_PENDIDIKAN
AS
SELECT
	A.ID_PEGAWAI		AS ID_PEGAWAI
,	A.KD_PROGRAM_STUDI  AS KD_PROGRAM_STUDI
,	A.TAHUN_MULAI       AS TAHUN_MULAI
,	A.TAHUN_SELESAI     AS TAHUN_SELESAI
,	A.KD_TINGKAT_IJAZAH AS KD_TINGKAT_IJAZAH
FROM 
	(T_PEGAWAI_DIDIK_FORMAL 	AS A
	JOIN V_PEGAWAI_DIDIK_MAX 	AS B)
WHERE (	(A.ID_PEGAWAI 	= B.ID_PEGAWAI)
AND 	(A.NO_URUT 		= B.URUT) );

/* V_PEGAWAI_PENATARAN_AKHIR */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_PENATARAN_AKHIR;

CREATE VIEW pas_smp.V_PEGAWAI_PENATARAN_AKHIR
AS
SELECT
	A.ID_PEGAWAI								AS ID_PEGAWAI
,	pas_smp.F_PEGAWAI_PENATARAN(A.ID_PEGAWAI)	AS NO_URUT
FROM
	T_PEGAWAI_PENATARAN	AS A
GROUP BY 
	A.ID_PEGAWAI;

/* V_PEGAWAI_PENATARAN_TAHUN */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_PENATARAN_TAHUN;

CREATE VIEW pas_smp.V_PEGAWAI_PENATARAN_TAHUN
AS
SELECT 
	C.ID_PEGAWAI					AS ID_PEGAWAI
,	B.KD_TAHUN_AJARAN             	AS KD_TAHUN_AJARAN
,	A.NO_URUT                     	AS NO_URUT
,	A.ID_PENATARAN                	AS ID_PENATARAN
,	A.KD_PENYELENGGARA_PENATARAN  	AS KD_PENYELENGGARA_PENATARAN
,	D.NM_PENYELENGGARA_PENATARAN  	AS NM_PENYELENGGARA_PENATARAN
,	A.KD_JENIS_PENATARAN          	AS KD_JENIS_PENATARAN
,	A.KD_MATA_PELAJARAN_DIAJARKAN 	AS KD_MATA_PELAJARAN_DIAJARKAN
,	A.TANGGAL_AWAL                	AS TGL_AWAL
,	A.TANGGAL_AKHIR               	AS TGL_AKHIR
,	A.JAM                         	AS JAM
FROM 
	(((	T_PEGAWAI_PENATARAN 		AS A
	JOIN T_SEKOLAH_IDENTITAS 		AS B)
    JOIN V_PEGAWAI_PENATARAN_AKHIR	AS C)
	JOIN R_PENYELENGGARA_PENATARAN 	AS D)
WHERE (	(c.ID_PEGAWAI 					= a.ID_PEGAWAI)
AND 	(c.NO_URUT 						= a.NO_URUT)
AND 	(d.KD_PENYELENGGARA_PENATARAN = a.KD_PENYELENGGARA_PENATARAN) );

/* V_PEGAWAI_DETIL */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_DETIL;

CREATE VIEW pas_smp.V_PEGAWAI_DETIL
AS
SELECT
	A.KD_TAHUN_AJARAN            	AS KD_TAHUN_AJARAN
,	A.ID_PEGAWAI					AS ID_PEGAWAI
,	A.KD_JENIS_KETENAGAAN        	AS KD_JENIS_KETENAGAAN
,	A.KD_JABATAN_PEGAWAI         	AS KD_JABATAN_PEGAWAI
,	B.KD_PANGKAT                 	AS KD_PANGKAT
,	B.NO_SK                      	AS NO_SK
,	B.TGL_SK                     	AS TGL_SK
,	B.KD_STATUS_PEGAWAI          	AS KD_STATUS_PEGAWAI
,	B.TMT_SK                     	AS TMT_SK
,	A.NM_PEGAWAI                 	AS NM_PEGAWAI
,	A.KOTA_LAHIR                 	AS KOTA_LAHIR
,	A.TGL_LAHIR                  	AS TGL_LAHIR
,	A.KD_JNS_KELAMIN             	AS KD_JNS_KELAMIN
,	A.KD_JENIS_PEGAWAI           	AS KD_JENIS_PEGAWAI
,	C.IST                        	AS IST
,	C.ANK                        	AS ANK
,	A.UMUR                       	AS UMUR
,	A.MS_KRJ_SK                  	AS MS_KRJ_SK
,	A.MS_KRJ_AWAL                	AS MS_KRJ_AWAL
,	A.THN_JADI_GURU              	AS THN_JADI_GURU
,	D.KD_TINGKAT_IJAZAH          	AS KD_TINGKAT_IJAZAH
,	D.KD_PROGRAM_STUDI           	AS KD_PROGRAM_STUDI
,	D.TAHUN_MULAI                	AS TAHUN_MULAI
,	D.TAHUN_SELESAI              	AS TAHUN_SELESAI
,	A.KD_TENAGA_ADMINISTRASI     	AS KD_TENAGA_ADMINISTRASI
,	E.NM_PENYELENGGARA_PENATARAN 	AS NM_PENYELENGGARA_PENATARAN
,	E.KD_JENIS_PENATARAN         	AS KD_JENIS_PENATARAN
,	E.JAM                        	AS JAM
,	E.KD_MATA_PELAJARAN_DIAJARKAN	AS KD_MATA_PELAJARAN_DIAJARKAN
,	(
		SELECT	
			G.STATUS_AKTIF		AS STATUS_AKTIF
		FROM 
			T_PEGAWAI_AKTIF	AS G
		WHERE (	(G.ID_PEGAWAI 		= A.ID_PEGAWAI)
		AND 	(G.KD_TAHUN_AJARAN 	= A.KD_TAHUN_AJARAN) )
	) AS STS_AKTIF
,	IF((A.MS_KRJ_SK <= 5),'1',IF(((A.MS_KRJ_SK > 5) AND (A.MS_KRJ_SK < 10)),'2',IF(((A.MS_KRJ_SK >= 10) AND (A.MS_KRJ_SK < 15)),'3',IF(((A.MS_KRJ_SK >= 15) AND (A.MS_KRJ_SK < 20)),'4',IF(((A.MS_KRJ_SK >= 20) AND (A.MS_KRJ_SK < 25)),'5',IF((A.MS_KRJ_SK >= 25),'6','0')))))) AS KD_MASA_KERJA
,	IF((A.UMUR < 20),'1',IF(((A.UMUR >= 20) AND (A.UMUR < 30)),'2',IF(((A.UMUR >= 30) AND (A.UMUR < 40)),'3',IF(((A.UMUR >= 40) AND (A.UMUR < 50)),'4',IF(((A.UMUR >= 50) AND (A.UMUR < 60)),'5',IF((A.UMUR >= 60),'6','0')))))) AS KD_USIA_PEGAWAI
,	LEFT(B.KD_PANGKAT,1)			AS KD_GOLONGAN_PANGKAT
FROM 
	((((	V_PEGAWAI_USIA_MASAKERJA 		AS A
	LEFT JOIN V_PEGAWAI_TGL_SK_PANGKAT		AS B ON ((A.ID_PEGAWAI = B.ID_PEGAWAI)))
	LEFT JOIN V_PEGAWAI_JML_KELUARGA 		AS C ON ((A.ID_PEGAWAI = C.ID_PEGAWAI)))
    LEFT JOIN V_PEGAWAI_LULUS_PENDIDIKAN	AS D ON ((A.ID_PEGAWAI = D.ID_PEGAWAI)))
	LEFT JOIN V_PEGAWAI_PENATARAN_TAHUN 	AS E ON (((A.ID_PEGAWAI = E.ID_PEGAWAI) AND (A.KD_TAHUN_AJARAN = E.KD_TAHUN_AJARAN))));

/* V_PEGAWAI_GURU_BUTUH */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_GURU_BUTUH;

CREATE VIEW pas_smp.V_PEGAWAI_GURU_BUTUH
AS
SELECT
	A.KD_TAHUN_AJARAN		AS KD_TAHUN_AJARAN
,	B.NPSN					AS NPSN
,	A.KD_KEL_MATA_PELAJARAN AS KD_KEL_MATA_PELAJARAN
,	SUM(A.JUMLAH_BUTUH)     AS BUTUH
FROM 
	( T_PEGAWAI_GURU_KEBUTUHAN	AS A
	JOIN T_SEKOLAH_IDENTITAS 	AS B)
WHERE B.KD_TAHUN_AJARAN = A.KD_TAHUN_AJARAN
GROUP BY 
	A.KD_TAHUN_AJARAN, B.NPSN, A.KD_KEL_MATA_PELAJARAN;

/* V_PEGAWAI_IJAZAH_TERTINGGI */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_IJAZAH_TERTINGGI;

CREATE VIEW pas_smp.V_PEGAWAI_IJAZAH_TERTINGGI
AS
SELECT	SQL_NO_CACHE
	B.KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_SLTA_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_SLTA_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_GURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_GURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_NONGURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_NONGURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_GURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_GURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_NONGURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_NONGURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_GURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_GURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_NONGURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_NONGURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_GURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_GURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_NONGURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_NONGURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_GURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_GURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_NONGURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_NONGURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_S3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_S3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_SLTA_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_SLTA_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_GURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_GURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_NONGURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_NONGURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_GURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_GURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_NONGURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_NONGURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_GURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_GURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_NONGURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_NONGURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_GURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_GURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_NONGURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_NONGURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_GURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_GURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_NONGURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_NONGURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTTP_S3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTTP_S3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_SLTA_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_SLTA_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_GURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_GURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_NONGURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_NONGURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_GURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_GURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_NONGURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_NONGURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_GURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_GURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_NONGURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_NONGURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_GURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_GURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_NONGURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_NONGURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_GURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_GURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_NONGURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_NONGURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUTDKTTP_S3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUTDKTTP_S3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_SLTA_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_SLTA_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_GURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_GURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_NONGURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_NONGURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_GURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_GURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_NONGURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_NONGURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_GURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_GURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_NONGURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_NONGURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_GURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_GURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_NONGURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_NONGURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_GURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_GURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_NONGURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_NONGURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUPUSAT_S3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUPUSAT_S3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_SLTA_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_SLTA_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_GURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_GURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_NONGURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_NONGURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_GURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_GURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_NONGURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_NONGURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_GURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_GURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_NONGURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_NONGURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_GURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_GURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_NONGURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_NONGURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_GURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_GURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_NONGURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_NONGURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURUDAERAH_S3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURUDAERAH_S3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_SLTA_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('01','02','03','04','05','06')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_SLTA_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_GURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('07','08')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_GURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_NONGURU_D1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '26') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_NONGURU_D1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_GURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('09','10')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_GURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_NONGURU_D2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '27') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_NONGURU_D2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_GURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('11','13')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_GURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_NONGURU_D3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH IN ('12','14')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_NONGURU_D3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_GURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '15') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_GURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_NONGURU_S1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '16') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_NONGURU_S1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_GURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '17') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_GURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_NONGURU_S2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '28') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_NONGURU_S2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_S3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','08','09','19','26','27','28','29','30','31','32','33')) AND (B.KD_TINGKAT_IJAZAH = '18') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_S3_P
FROM
	V_PEGAWAI_DETIL	AS B
WHERE 
	B.STS_AKTIF = '1'
GROUP BY 
	B.KD_TAHUN_AJARAN;

/* V_PEGAWAI_IJAZAH_TINGGI */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_IJAZAH_TINGGI;

CREATE VIEW pas_smp.V_PEGAWAI_IJAZAH_TINGGI
AS
SELECT
	ID_PEGAWAI				AS ID_PEGAWAI
,	MAX(KD_TINGKAT_IJAZAH)	AS KD_TINGKAT_IJAZAH
FROM
	T_PEGAWAI_DIDIK_FORMAL
WHERE 
	KD_STATUS_LULUS = '1'
GROUP BY 
	ID_PEGAWAI;

/* V_PEGAWAI_JML_TENAGA_ADM */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_JML_TENAGA_ADM;

CREATE VIEW pas_smp.V_PEGAWAI_JML_TENAGA_ADM
AS
SELECT
    A.KD_TAHUN_AJARAN   AS KD_TAHUN_AJARAN
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '1') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS KEP_TU_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '1') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS KEP_TU_P
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '2') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS BENDAHARA_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '2') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS BENDAHARA_P
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '3') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS PETUGAS_INS_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '3') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS PETUGAS_INS_P
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '4') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS LABORAN_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '4') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS LABORAN_P
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '5') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS PERPUS_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '5') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS PERPUS_P
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '6') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS JURU_BENGKEL_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '6') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS JURU_BENGKEL_P
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '7') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS JURU_KETIK_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '7') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS JURU_KETIK_P
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '8') AND (A.KD_JNS_KELAMIN = '1')),1,0)) AS PENJAGA_SEK_L
,	SUM(IF(((A.KD_TENAGA_ADMINISTRASI = '8') AND (A.KD_JNS_KELAMIN = '2')),1,0)) AS PENJAGA_SEK_P
FROM        V_PEGAWAI_DETIL AS A
WHERE       A.STS_AKTIF             = '1'
AND         A.KD_JENIS_KETENAGAAN   NOT IN ('1','6')
GROUP BY    A.KD_TAHUN_AJARAN;

/* V_PEGAWAI_MASA_KERJA */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_MASA_KERJA;

CREATE VIEW pas_smp.V_PEGAWAI_MASA_KERJA
AS
SELECT	SQL_NO_CACHE
	B.KD_TAHUN_AJARAN AS KD_TAHUN_AJARAN
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.UMUR < 20)),1,0)) AS KASEK_UMUR_20
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.UMUR >= 20) AND (B.UMUR < 30)),1,0)) AS KASEK_UMUR_29
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.UMUR >= 30) AND (B.UMUR < 40)),1,0)) AS KASEK_UMUR_39
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.UMUR >= 40) AND (B.UMUR < 50)),1,0)) AS KASEK_UMUR_49
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.UMUR >= 50) AND (B.UMUR < 60)),1,0)) AS KASEK_UMUR_59
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.UMUR >= 60)),1,0)) AS KASEK_UMUR_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.MS_KRJ_AWAL < 5)),1,0)) AS KASEK_KRJ_5
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.MS_KRJ_AWAL >= 5) AND (B.MS_KRJ_AWAL < 10)),1,0)) AS KASEK_KRJ_9
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.MS_KRJ_AWAL >= 10) AND (B.MS_KRJ_AWAL < 15)),1,0)) AS KASEK_KRJ_14
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.MS_KRJ_AWAL >= 15) AND (B.MS_KRJ_AWAL < 20)),1,0)) AS KASEK_KRJ_19
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.MS_KRJ_AWAL >= 20) AND (B.MS_KRJ_AWAL < 25)),1,0)) AS KASEK_KRJ_24
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('15','20','21','22','23','24')) AND (B.MS_KRJ_AWAL >= 25)),1,0)) AS KASEK_KRJ_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.UMUR < 20)),1,0)) AS GURUTTP_UMUR_20
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.UMUR >= 20) AND (B.UMUR < 30)),1,0)) AS GURUTTP_UMUR_29
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.UMUR >= 30) AND (B.UMUR < 40)),1,0)) AS GURUTTP_UMUR_39
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.UMUR >= 40) AND (B.UMUR < 50)),1,0)) AS GURUTTP_UMUR_49
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.UMUR >= 50) AND (B.UMUR < 60)),1,0)) AS GURUTTP_UMUR_59
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.UMUR >= 60)),1,0)) AS GURUTTP_UMUR_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.MS_KRJ_AWAL < 5)),1,0)) AS GURUTTP_KRJ_5
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.MS_KRJ_AWAL >= 5) AND (B.MS_KRJ_AWAL < 10)),1,0)) AS GURUTTP_KRJ_9
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.MS_KRJ_AWAL >= 10) AND (B.MS_KRJ_AWAL < 15)),1,0)) AS GURUTTP_KRJ_14
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.MS_KRJ_AWAL >= 15) AND (B.MS_KRJ_AWAL < 20)),1,0)) AS GURUTTP_KRJ_19
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.MS_KRJ_AWAL >= 20) AND (B.MS_KRJ_AWAL < 25)),1,0)) AS GURUTTP_KRJ_24
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','03','10','11','12','25')) AND (B.MS_KRJ_AWAL >= 25)),1,0)) AS GURUTTP_KRJ_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.UMUR < 20)),1,0)) AS GURUPST_UMUR_20
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.UMUR >= 20) AND (B.UMUR < 30)),1,0)) AS GURUPST_UMUR_29
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.UMUR >= 30) AND (B.UMUR < 40)),1,0)) AS GURUPST_UMUR_39
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.UMUR >= 40) AND (B.UMUR < 50)),1,0)) AS GURUPST_UMUR_49
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.UMUR >= 50) AND (B.UMUR < 60)),1,0)) AS GURUPST_UMUR_59
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.UMUR >= 60)),1,0)) AS GURUPST_UMUR_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.MS_KRJ_AWAL < 5)),1,0)) AS GURUPST_KRJ_5
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.MS_KRJ_AWAL >= 5) AND (B.MS_KRJ_AWAL < 10)),1,0)) AS GURUPST_KRJ_9
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.MS_KRJ_AWAL >= 10) AND (B.MS_KRJ_AWAL < 15)),1,0)) AS GURUPST_KRJ_14
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.MS_KRJ_AWAL >= 15) AND (B.MS_KRJ_AWAL < 20)),1,0)) AS GURUPST_KRJ_19
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.MS_KRJ_AWAL >= 20) AND (B.MS_KRJ_AWAL < 25)),1,0)) AS GURUPST_KRJ_24
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.MS_KRJ_AWAL >= 25)),1,0)) AS GURUPST_KRJ_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.UMUR < 20)),1,0)) AS GURUDRH_UMUR_20
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.UMUR >= 20) AND (B.UMUR < 30)),1,0)) AS GURUDRH_UMUR_29
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.UMUR >= 30) AND (B.UMUR < 40)),1,0)) AS GURUDRH_UMUR_39
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.UMUR >= 40) AND (B.UMUR < 50)),1,0)) AS GURUDRH_UMUR_49
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.UMUR >= 50) AND (B.UMUR < 60)),1,0)) AS GURUDRH_UMUR_59
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.UMUR >= 60)),1,0)) AS GURUDRH_UMUR_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.MS_KRJ_AWAL < 5)),1,0)) AS GURUDRH_KRJ_5
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.MS_KRJ_AWAL >= 5) AND (B.MS_KRJ_AWAL < 10)),1,0)) AS GURUDRH_KRJ_9
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.MS_KRJ_AWAL >= 10) AND (B.MS_KRJ_AWAL < 15)),1,0)) AS GURUDRH_KRJ_14
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.MS_KRJ_AWAL >= 15) AND (B.MS_KRJ_AWAL < 20)),1,0)) AS GURUDRH_KRJ_19
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.MS_KRJ_AWAL >= 20) AND (B.MS_KRJ_AWAL < 25)),1,0)) AS GURUDRH_KRJ_24
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.MS_KRJ_AWAL >= 25)),1,0)) AS GURUDRH_KRJ_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.UMUR < 20)),1,0)) AS GURUTAKTTP_UMUR_20
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.UMUR >= 20) AND (B.UMUR < 30)),1,0)) AS GURUTAKTTP_UMUR_29
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.UMUR >= 30) AND (B.UMUR < 40)),1,0)) AS GURUTAKTTP_UMUR_39
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.UMUR >= 40) AND (B.UMUR < 50)),1,0)) AS GURUTAKTTP_UMUR_49
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.UMUR >= 50) AND (B.UMUR < 60)),1,0)) AS GURUTAKTTP_UMUR_59
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.UMUR >= 60)),1,0)) AS GURUTAKTTP_UMUR_99
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.MS_KRJ_AWAL < 5)),1,0)) AS GURUTAKTTP_KRJ_5
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.MS_KRJ_AWAL >= 5) AND (B.MS_KRJ_AWAL < 10)),1,0)) AS GURUTAKTTP_KRJ_9
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.MS_KRJ_AWAL >= 10) AND (B.MS_KRJ_AWAL < 15)),1,0)) AS GURUTAKTTP_KRJ_14
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.MS_KRJ_AWAL >= 15) AND (B.MS_KRJ_AWAL < 20)),1,0)) AS GURUTAKTTP_KRJ_19
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.MS_KRJ_AWAL >= 20) AND (B.MS_KRJ_AWAL < 25)),1,0)) AS GURUTAKTTP_KRJ_24
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17','18')) AND (B.MS_KRJ_AWAL >= 25)),1,0)) AS GURUTAKTTP_KRJ_99
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.UMUR < 20)),1,0)) AS ADMIN_UMUR_20
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.UMUR >= 20) AND (B.UMUR < 30)),1,0)) AS ADMIN_UMUR_29
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.UMUR >= 30) AND (B.UMUR < 40)),1,0)) AS ADMIN_UMUR_39
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.UMUR >= 40) AND (B.UMUR < 50)),1,0)) AS ADMIN_UMUR_49
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.UMUR >= 50) AND (B.UMUR < 60)),1,0)) AS ADMIN_UMUR_59
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.UMUR >= 60)),1,0)) AS ADMIN_UMUR_99
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.MS_KRJ_AWAL < 5)),1,0)) AS ADMIN_KRJ_5
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.MS_KRJ_AWAL >= 5) AND (B.MS_KRJ_AWAL < 10)),1,0)) AS ADMIN_KRJ_9
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.MS_KRJ_AWAL >= 10) AND (B.MS_KRJ_AWAL < 15)),1,0)) AS ADMIN_KRJ_14
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.MS_KRJ_AWAL >= 15) AND (B.MS_KRJ_AWAL < 20)),1,0)) AS ADMIN_KRJ_19
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.MS_KRJ_AWAL >= 20) AND (B.MS_KRJ_AWAL < 25)),1,0)) AS ADMIN_KRJ_24
,	SUM(IF(((B.KD_TENAGA_ADMINISTRASI IS NOT NULL) AND (B.MS_KRJ_AWAL > 25)),1,0)) AS ADMIN_KRJ_99
FROM
	V_PEGAWAI_DETIL	AS B
WHERE 
	B.STS_AKTIF = '1'
GROUP BY 
	B.KD_TAHUN_AJARAN;

/* V_PEGAWAI_STATUS */
DROP VIEW IF EXISTS pas_smp.V_PEGAWAI_STATUS;

CREATE VIEW pas_smp.V_PEGAWAI_STATUS
AS
SELECT	SQL_NO_CACHE
	B.KD_TAHUN_AJARAN AS KD_TAHUN_AJARAN
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '15') AND (B.KD_GOLONGAN_PANGKAT = '2') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TTP_2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '15') AND (B.KD_GOLONGAN_PANGKAT = '2') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TTP_2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '15') AND (B.KD_GOLONGAN_PANGKAT = '3') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TTP_3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '15') AND (B.KD_GOLONGAN_PANGKAT = '3') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TTP_3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '15') AND (B.KD_GOLONGAN_PANGKAT = '4') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TTP_4_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '15') AND (B.KD_GOLONGAN_PANGKAT = '4') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TTP_4_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '20') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TTP_Y_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '20') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TTP_Y_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '21') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TAKTTP_PNS_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '21') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TAKTTP_PNS_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '22') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TAKTTP_BPNS_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '22') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TAKTTP_BPNS_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '23') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TAKTTP_PST_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '23') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TAKTTP_PST_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '24') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS KASEK_TAKTTP_DRH_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '24') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS KASEK_TAKTTP_DRH_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','10','11','12','25')) AND (B.KD_GOLONGAN_PANGKAT = '2') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TTP_2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','10','11','12','25')) AND (B.KD_GOLONGAN_PANGKAT = '2') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TTP_2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','10','11','12','25')) AND (B.KD_GOLONGAN_PANGKAT = '3') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TTP_3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','10','11','12','25')) AND (B.KD_GOLONGAN_PANGKAT = '3') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TTP_3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','10','11','12','25')) AND (B.KD_GOLONGAN_PANGKAT = '4') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TTP_4_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('01','02','10','11','12','25')) AND (B.KD_GOLONGAN_PANGKAT = '4') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TTP_4_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '03') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TTP_Y_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '03') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TTP_Y_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TAKTTP_PNS_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('06','17')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TAKTTP_PNS_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '18') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TAKTTP_BPNS_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '18') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TAKTTP_BPNS_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TAKTTP_PST_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '04') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TAKTTP_PST_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS GURU_TAKTTP_DRH_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI = '05') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS GURU_TAKTTP_DRH_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '1') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_TTP_1_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '1') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_TTP_1_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '2') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_TTP_2_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '2') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_TTP_2_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '3') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_TTP_3_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '3') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_TTP_3_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '4') AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_TTP_4_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('19','26','30')) AND (B.KD_GOLONGAN_PANGKAT = '4') AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_TTP_4_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','27','31')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_TTP_Y_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('07','27','31')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_TTP_Y_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('09','28','32')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_TAKTTP_PNS_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('09','28','32')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_TAKTTP_PNS_P
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('08','29','33')) AND (B.KD_JNS_KELAMIN = '1')),1,0)) AS ADMIN_TAKTTP_BPNS_L
,	SUM(IF(((B.KD_JENIS_PEGAWAI IN ('08','29','33')) AND (B.KD_JNS_KELAMIN = '2')),1,0)) AS ADMIN_TAKTTP_BPNS_P
FROM
	V_PEGAWAI_DETIL	AS B
WHERE 
	B.STS_AKTIF = '1'
GROUP BY 
	B.KD_TAHUN_AJARAN;

/* V_ROMBEL_JML */
DROP VIEW IF EXISTS pas_smp.V_ROMBEL_JML;

CREATE VIEW pas_smp.V_ROMBEL_JML
AS
SELECT
	A.KD_TAHUN_AJARAN 							AS KD_TAHUN_AJARAN
,	SUM(IF((A.KD_TINGKAT_KELAS = '01'),1,0)) 	AS KLS_UMUM1
,	SUM(IF((A.KD_TINGKAT_KELAS = '02'),1,0)) 	AS KLS_UMUM2
,	SUM(IF((A.KD_TINGKAT_KELAS = '03'),1,0)) 	AS KLS_UMUM3
FROM 
	(T_PEGAWAI_ROMBEL 			AS A
	JOIN T_SEKOLAH_IDENTITAS 	AS B)
GROUP BY 
	A.KD_TAHUN_AJARAN;

/* V_SISWA */
DROP VIEW IF EXISTS pas_smp.V_SISWA;

CREATE VIEW pas_smp.V_SISWA
AS
SELECT
	A.KD_TAHUN_AJARAN  				AS KD_TAHUN_AJARAN
,	A.NPSN             				AS NPSN
,	B.ID_SISWA              		AS ID_SISWA
,	B.KD_TINGKAT_KELAS 				AS KD_TINGKAT_KELAS
,	B.KD_ROMBEL        				AS KD_ROMBEL
,	IFNULL(B.KD_STATUS_SISWA,'0') 	AS KD_PUTUS_SEKOLAH
,	IFNULL(B.KD_EBTA,'0') 			AS KD_EBTA
,	C.KD_AGAMA         				AS KD_AGAMA
,	C.KD_JENIS_KELAMIN 				AS KD_JNS_KELAMIN
,	(CAST(LEFT(D.NM_TAHUN_AJARAN,4) AS DECIMAL) - YEAR(C.TANGGAL_LAHIR)) AS USIA_SISWA
,	IF((C.STATUS_SISWA = '0'),'0',IF((C.STATUS_SISWA = '1'),'2',IF((C.STATUS_SISWA IN ('2','3','4')),'3',NULL))) AS KD_STATUS_SISWA
,	(
		SELECT
			D.KD_JENIS_SEKOLAH AS KD_JENIS_SEKOLAH
		FROM
			R_ASAL_SEKOLAH D
		WHERE 
			D.ASAL_SD = C.ASAL_SD
	) AS JENIS_SMP
,	IF((C.STATUS_SISWA IN ('2','3','4')),IF((C.STATUS_SISWA = '2'),'1',IF((C.STATUS_SISWA = '3'),'2','3')),NULL) AS KD_MUTASI
FROM 
	(((	T_SEKOLAH_IDENTITAS	AS A
	JOIN T_SISWA_TINGKAT 	AS B)
    JOIN T_SISWA 			AS C)
	JOIN R_TAHUN_AJARAN 	AS D)
WHERE (	(B.KD_TAHUN_AJARAN 	= A.KD_TAHUN_AJARAN)
AND 	(C.ID_SISWA 		= B.ID_SISWA)
AND 	(D.KD_TAHUN_AJARAN 	= A.KD_TAHUN_AJARAN) );

/* V_SISWA_THN_AJARAN */
DROP VIEW IF EXISTS pas_smp.V_SISWA_THN_AJARAN;

CREATE VIEW pas_smp.V_SISWA_THN_AJARAN
AS
SELECT
	ID_SISWA			AS ID_SISWA
,	KD_TAHUN_AJARAN		AS KD_TAHUN_AJARAN
,	KD_TINGKAT_KELAS	AS KD_TINGKAT_KELAS
FROM 
	T_SISWA_TINGKAT;

/* V_SISWA_THN_SEBELUMNYA */
DROP VIEW IF EXISTS pas_smp.V_SISWA_THN_SEBELUMNYA;

CREATE VIEW pas_smp.V_SISWA_THN_SEBELUMNYA
AS
SELECT
	A.ID_SISWA			AS ID_SISWA
,	A.KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	A.KD_TINGKAT_KELAS	AS KD_TINGKAT_KELAS
FROM 
	(T_SISWA_TINGKAT			AS A
	JOIN V_SISWA_THN_AJARAN 	AS B)
WHERE (	(B.ID_SISWA 			= A.ID_SISWA)
AND 	(B.KD_TINGKAT_KELAS 	= A.KD_TINGKAT_KELAS)
AND 	((CAST(B.KD_TAHUN_AJARAN AS DECIMAL) - 1) = CAST(B.KD_TAHUN_AJARAN AS DECIMAL)));

/* V_SISWA_MENGULANG */
DROP VIEW IF EXISTS pas_smp.V_SISWA_MENGULANG;

CREATE VIEW pas_smp.V_SISWA_MENGULANG
AS
SELECT
	B.KD_TINGKAT_KELAS	AS KD_TINGKAT_KELAS
,	B.KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	A.KD_JENIS_KELAMIN	AS KD_JNS_KELAMIN
,	COUNT(0)			AS JUMLAH
FROM 
	(( T_SISWA 					AS A
    JOIN T_SISWA_TINGKAT 		AS B)
	JOIN V_SISWA_THN_SEBELUMNYA AS C)
WHERE (	(A.ID_SISWA 		= B.ID_SISWA)
AND 	(C.ID_SISWA 		= B.ID_SISWA)
AND 	(C.KD_TAHUN_AJARAN 	= B.KD_TAHUN_AJARAN)
AND 	(C.KD_TINGKAT_KELAS = B.KD_TINGKAT_KELAS) )
GROUP BY 
	B.KD_TINGKAT_KELAS, B.KD_TAHUN_AJARAN, A.KD_JENIS_KELAMIN;

/* V_SISWA_JML_MENGULANG */
DROP VIEW IF EXISTS pas_smp.V_SISWA_JML_MENGULANG;

CREATE VIEW pas_smp.V_SISWA_JML_MENGULANG
AS
SELECT
	KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '1')),JUMLAH,0)) AS U1L
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '2')),JUMLAH,0)) AS U1P
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '1')),JUMLAH,0)) AS U2L
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '2')),JUMLAH,0)) AS U2P
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '1')),JUMLAH,0)) AS U3L
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '2')),JUMLAH,0)) AS U3P
FROM 
	V_SISWA_MENGULANG
GROUP BY 
	KD_TAHUN_AJARAN;

/* V_SISWA_MUTASI */
DROP VIEW IF EXISTS pas_smp.V_SISWA_MUTASI;

CREATE VIEW pas_smp.V_SISWA_MUTASI
AS
SELECT
	B.KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	A.ID_SISWA			AS ID_SISWA
,	A.KD_JENIS_KELAMIN 	AS KD_JNS_KELAMIN
,	B.KD_TINGKAT_KELAS 	AS KD_TINGKAT_KELAS
,	A.STATUS_SISWA     	AS STATUS_SISWA
FROM 
	(T_SISWA 				AS A
	JOIN T_SISWA_TINGKAT 	AS B)
WHERE (	(A.ID_SISWA = B.ID_SISWA)
AND 	((A.STATUS_SISWA = '2') OR (A.STATUS_SISWA = '3') OR (A.STATUS_SISWA = '4')) )
GROUP BY 
	B.KD_TAHUN_AJARAN, A.ID_SISWA, A.KD_JENIS_KELAMIN, B.KD_TINGKAT_KELAS, A.STATUS_SISWA;

/* V_SISWA_JML_MUTASI */
DROP VIEW IF EXISTS pas_smp.V_SISWA_JML_MUTASI;

CREATE VIEW pas_smp.V_SISWA_JML_MUTASI
AS
SELECT
	KD_TAHUN_AJARAN AS KD_TAHUN_AJARAN
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '2')),1,0)) AS KOTAINI_1L
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '2')),1,0)) AS KOTAINI_1P
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '2')),1,0)) AS KOTAINI_2L
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '2')),1,0)) AS KOTAINI_2P
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '2')),1,0)) AS KOTAINI_3L
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '2')),1,0)) AS KOTAINI_3P
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '3')),1,0)) AS KOTALAIN_1L
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '3')),1,0)) AS KOTALAIN_1P
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '3')),1,0)) AS KOTALAIN_2L
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '3')),1,0)) AS KOTALAIN_2P
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '3')),1,0)) AS KOTALAIN_3L
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '3')),1,0)) AS KOTALAIN_3P
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '4')),1,0)) AS KELUAR_1L
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '4')),1,0)) AS KELUAR_1P
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '4')),1,0)) AS KELUAR_2L
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '4')),1,0)) AS KELUAR_2P
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '1') AND (STATUS_SISWA = '4')),1,0)) AS KELUAR_3L
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '2') AND (STATUS_SISWA = '4')),1,0)) AS KELUAR_3P
FROM 
	V_SISWA_MUTASI
GROUP BY 
	KD_TAHUN_AJARAN;

/* V_SISWA_THN_PUTUS */
DROP VIEW IF EXISTS pas_smp.V_SISWA_THN_PUTUS;

CREATE VIEW pas_smp.V_SISWA_THN_PUTUS
AS
SELECT
	A.ID_SISWA				AS ID_SISWA
,	MAX(B.KD_TAHUN_AJARAN)	AS THN_PUTUS
FROM 
	(T_SISWA 				AS A
	JOIN T_SISWA_TINGKAT 	AS B)
WHERE (	(B.ID_SISWA 	= A.ID_SISWA)
AND 	(A.STATUS_SISWA = '1') )
GROUP BY 
	A.ID_SISWA;

/* V_SISWA_PUTUS_SEKOLAH */
DROP VIEW IF EXISTS pas_smp.V_SISWA_PUTUS_SEKOLAH;

CREATE VIEW pas_smp.V_SISWA_PUTUS_SEKOLAH
AS
SELECT
	B.KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	A.ID_SISWA			AS ID_SISWA
,	A.KD_JENIS_KELAMIN	AS KD_JNS_KELAMIN
,	B.KD_TINGKAT_KELAS	AS KD_TINGKAT_KELAS
FROM 
	((T_SISWA 				AS A
    JOIN T_SISWA_TINGKAT 	AS B)
	JOIN V_SISWA_THN_PUTUS 	AS C)
WHERE (	(A.ID_SISWA 		= B.ID_SISWA)
AND 	(B.ID_SISWA 		= C.ID_SISWA)
AND 	(B.KD_TAHUN_AJARAN 	= C.THN_PUTUS) )
GROUP BY 
	B.KD_TAHUN_AJARAN, A.ID_SISWA, A.KD_JENIS_KELAMIN, B.KD_TINGKAT_KELAS;

/* V_SISWA_JML_PUTUS_SEKOLAH */
DROP VIEW IF EXISTS pas_smp.V_SISWA_JML_PUTUS_SEKOLAH;

CREATE VIEW pas_smp.V_SISWA_JML_PUTUS_SEKOLAH
AS
SELECT
	KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '1')),1,0)) AS U1L
,	SUM(IF(((KD_TINGKAT_KELAS = '01') AND (KD_JNS_KELAMIN = '2')),1,0)) AS U1P
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '1')),1,0)) AS U2L
,	SUM(IF(((KD_TINGKAT_KELAS = '02') AND (KD_JNS_KELAMIN = '2')),1,0)) AS U2P
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '1')),1,0)) AS U3L
,	SUM(IF(((KD_TINGKAT_KELAS = '03') AND (KD_JNS_KELAMIN = '2')),1,0)) AS U3P
FROM 
	V_SISWA_PUTUS_SEKOLAH
GROUP BY 
	KD_TAHUN_AJARAN;

/* V_SISWA_LULUS_UAN */
DROP VIEW IF EXISTS pas_smp.V_SISWA_LULUS_UAN;

CREATE VIEW pas_smp.V_SISWA_LULUS_UAN
AS
SELECT
	B.KD_TAHUN_AJARAN 						AS KD_TAHUN_AJARAN
,	SUM(IF((A.KD_JENIS_KELAMIN = '1'),1,0)) AS LL
,	SUM(IF((A.KD_JENIS_KELAMIN = '2'),1,0)) AS PP
FROM 
	((T_SISWA 				AS A
    JOIN T_SISWA_TINGKAT 	AS B)
	JOIN T_NILAI_STTB 		AS C)
WHERE (	(A.ID_SISWA			= B.ID_SISWA)
AND 	(B.ID_SISWA			= C.ID_SISWA)
AND 	(B.KD_TAHUN_AJARAN 	= C.KD_TAHUN_AJARAN)
AND 	(B.KD_TINGKAT_KELAS = C.KD_TINGKAT_KELAS)
AND 	(B.KD_ROMBEL 		= C.KD_ROMBEL))
GROUP BY 
	B.KD_TAHUN_AJARAN;

/* V_SISWA_NO_INDUK */
DROP VIEW IF EXISTS pas_smp.V_SISWA_NO_INDUK;

CREATE VIEW pas_smp.V_SISWA_NO_INDUK
AS
SELECT
	A.ID_SISWA			AS ID_SISWA
,	A.NIS				AS NIS
,	B.KD_TAHUN_AJARAN  	AS KD_TAHUN_AJARAN
,	B.KD_TINGKAT_KELAS 	AS KD_TINGKAT_KELAS
,	B.KD_ROMBEL        	AS KD_ROMBEL
,	A.NM_SISWA         	AS NM_SISWA
FROM 
	(T_SISWA 				AS A
	JOIN T_SISWA_TINGKAT 	AS B)
WHERE (	(A.ID_SISWA = B.ID_SISWA)
AND 	((A.STATUS_SISWA NOT IN('1','4','5','6')) OR ISNULL(A.STATUS_SISWA)) );

/* V_SISWA_NO_INDUK_PINDAHAN */
DROP VIEW IF EXISTS pas_smp.V_SISWA_NO_INDUK_PINDAHAN;

CREATE VIEW pas_smp.V_SISWA_NO_INDUK_PINDAHAN
AS
SELECT
	A.ID_SISWA	AS ID_SISWA
,	A.NIS 		AS NIS
,	A.NM_SISWA 	AS NM_SISWA
FROM 
	T_SISWA 	AS A
WHERE (((A.STATUS_SISWA IN('2','3')) OR ISNULL(A.STATUS_SISWA))
AND NOT(A.ID_SISWA IN(SELECT B.ID_SISWA AS ID_SISWA FROM T_SISWA_TINGKAT B)));

/* V_SISWA_PESERTA_UAN */
DROP VIEW IF EXISTS pas_smp.V_SISWA_PESERTA_UAN;

CREATE VIEW pas_smp.V_SISWA_PESERTA_UAN
AS
SELECT
	B.KD_TAHUN_AJARAN 		AS KD_TAHUN_AJARAN
,	SUM(IF((A.KD_JENIS_KELAMIN = '1'),1,0)) AS PL
,	SUM(IF((A.KD_JENIS_KELAMIN = '2'),1,0)) AS PP
FROM 
	(T_SISWA 				AS A
	JOIN T_SISWA_TINGKAT 	AS B)
WHERE (	(A.ID_SISWA = B.ID_SISWA)
AND 	(B.KD_TINGKAT_KELAS = '03') )
GROUP BY B.KD_TAHUN_AJARAN;

/* V_SISWA_TUNA */
DROP VIEW IF EXISTS pas_smp.V_SISWA_TUNA;

CREATE VIEW pas_smp.V_SISWA_TUNA
AS
SELECT
	B.KD_TAHUN_AJARAN	AS KD_TAHUN_AJARAN
,	A.KD_KETUNAAN		AS KD_KETUNAAN
,	(
		SELECT	COUNT(*)
		FROM (T_SISWA_TINGKAT C JOIN T_SISWA_INFO D)
		WHERE (	(D.KD_KETUNAAN 		= A.KD_KETUNAAN)
		AND 	(D.ID_SISWA 		= C.ID_SISWA)
		AND 	(C.KD_TAHUN_AJARAN 	= B.KD_TAHUN_AJARAN)
		AND 	(C.KD_TINGKAT_KELAS = '01')
		AND 	(C.KD_JENIS_KELAMIN = '1') )
	) AS JUMLAH_KELAS1_LAKI
,	(
		SELECT	COUNT(*)
		FROM (T_SISWA_TINGKAT C JOIN T_SISWA_INFO D)
		WHERE (	(D.KD_KETUNAAN 		= A.KD_KETUNAAN)
		AND 	(D.ID_SISWA 		= C.ID_SISWA)
		AND 	(C.KD_TAHUN_AJARAN 	= B.KD_TAHUN_AJARAN)
		AND 	(C.KD_TINGKAT_KELAS = '01')
		AND 	(C.KD_JENIS_KELAMIN = '2') )
	) AS JUMLAH_KELAS1_WANITA
,	(
		SELECT	COUNT(*)
		FROM (T_SISWA_TINGKAT C JOIN T_SISWA_INFO D)
		WHERE (	(D.KD_KETUNAAN 		= A.KD_KETUNAAN)
		AND 	(D.ID_SISWA 		= C.ID_SISWA)
		AND 	(C.KD_TAHUN_AJARAN 	= B.KD_TAHUN_AJARAN)
		AND 	(C.KD_TINGKAT_KELAS = '02')
		AND 	(C.KD_JENIS_KELAMIN = '1') )
	) AS JUMLAH_KELAS2_LAKI
,	(
		SELECT	COUNT(*)
		FROM (T_SISWA_TINGKAT C JOIN T_SISWA_INFO D)
		WHERE (	(D.KD_KETUNAAN 		= A.KD_KETUNAAN)
		AND 	(D.ID_SISWA 		= C.ID_SISWA)
		AND 	(C.KD_TAHUN_AJARAN 	= B.KD_TAHUN_AJARAN)
		AND 	(C.KD_TINGKAT_KELAS = '02')
		AND 	(C.KD_JENIS_KELAMIN = '2') )
	) AS JUMLAH_KELAS2_WANITA
,	(
		SELECT	COUNT(*)
		FROM (T_SISWA_TINGKAT C JOIN T_SISWA_INFO D)
		WHERE (	(D.KD_KETUNAAN 		= A.KD_KETUNAAN)
		AND 	(D.ID_SISWA 		= C.ID_SISWA)
		AND 	(C.KD_TAHUN_AJARAN 	= B.KD_TAHUN_AJARAN)
		AND 	(C.KD_TINGKAT_KELAS = '03')
		AND 	(C.KD_JENIS_KELAMIN = '1') )
	) AS JUMLAH_KELAS3_LAKI
,	(
		SELECT	COUNT(*)
		FROM (T_SISWA_TINGKAT C JOIN T_SISWA_INFO D)
		WHERE (	(D.KD_KETUNAAN 		= A.KD_KETUNAAN)
		AND 	(D.ID_SISWA 		= C.ID_SISWA)
		AND 	(C.KD_TAHUN_AJARAN 	= B.KD_TAHUN_AJARAN)
		AND 	(C.KD_TINGKAT_KELAS = '03')
		AND 	(C.KD_JENIS_KELAMIN = '2') )
	) AS JUMLAH_KELAS3_WANITA
FROM (R_KETUNAAN A JOIN R_TAHUN_AJARAN B);

/* V_SISWA_UMUR */
DROP VIEW IF EXISTS pas_smp.V_SISWA_UMUR;

CREATE VIEW pas_smp.V_SISWA_UMUR
AS
SELECT	
	ID_SISWA			AS ID_SISWA
,	KD_JENIS_KELAMIN	AS KD_JNS_KELAMIN
,	IF(((MONTH(NOW()) - MONTH(TANGGAL_LAHIR)) >= 0),(YEAR(NOW()) - YEAR(TANGGAL_LAHIR)),((YEAR(NOW()) - YEAR(TANGGAL_LAHIR)) - 1)) AS UMUR
FROM T_SISWA;

/* V_TAHUN_BERLAKU */
DROP VIEW IF EXISTS pas_smp.V_TAHUN_BERLAKU;

CREATE VIEW pas_smp.V_TAHUN_BERLAKU
AS
SELECT
	A.KD_KURIKULUM	AS KD_THN_BERLAKU
,	B.NM_KURIKULUM	AS NM_TAHUN_BERLAKU
FROM 
	(T_KUR_KURIKULUM A JOIN R_KURIKULUM B)
WHERE 
	(B.KD_KURIKULUM = A.KD_KURIKULUM)
GROUP BY 
	A.KD_KURIKULUM, B.NM_KURIKULUM;

/* V_WILAYAH */
DROP VIEW IF EXISTS pas_smp.V_WILAYAH;

CREATE VIEW pas_smp.V_WILAYAH
AS
SELECT
	0						AS ID_PRO
,	0						AS ID_KAB
,	0 						AS ID_KEC
,	NULL 					AS KD_PROPINSI
,	NULL 					AS KD_KABUPATEN
,	NULL 					AS KD_KECAMATAN
,	NULL 					AS NM_PROPINSI
,	NULL 					AS NM_KABUPATEN
,	NULL 					AS NM_KECAMATAN
,	NULL 					AS AW_PRO
,	NULL 					AS AK_PRO
,	NULL 					AS AW_KAB
,	NULL 					AS AK_KAB
UNION
SELECT
	B.ID_PROPINSI			AS ID_PRO
,	A.ID_KABUPATEN			AS ID_KAB
,	A.ID_KECAMATAN 			AS ID_KEC
,	C.KD_PROPINSI			AS KD_PROPINSI
,	B.KD_KABUPATEN 			AS KD_KABUPATEN
,	A.KD_KECAMATAN 			AS KD_KECAMATAN
,	C.NM_PROPINSI 			AS NM_PROPINSI
,	D.NM_KABUPATEN 			AS NM_KABUPATEN
,	E.NM_KECAMATAN 			AS NM_KECAMATAN
,	C.TAHUN_AWAL 			AS AW_PRO
,	C.TAHUN_AKHIR 			AS AK_PRO
,	B.TAHUN_AWAL 			AS AW_KAB
,	B.TAHUN_AKHIR 			AS AK_KAB
FROM 
	((((	T_KABUPATEN_KECAMATAN	AS A 
	JOIN 	T_PROPINSI_KABUPATEN 	AS B) 
	JOIN 	R_PROPINSI 				AS C)
	JOIN 	R_KABUPATEN 			AS D) 
	JOIN 	R_KECAMATAN 			AS E)
WHERE (	(B.ID_KABUPATEN 	= A.ID_KABUPATEN) 
AND		ISNULL(B.TAHUN_AKHIR) 
AND 	(C.ID_PROPINSI 		= B.ID_PROPINSI) 
AND 	ISNULL(C.TAHUN_AKHIR) 
AND 	(D.ID_KABUPATEN 	= A.ID_KABUPATEN) 
AND 	(E.ID_KECAMATAN 	= A.ID_KECAMATAN) );

/* V_WILAYAH_X */
DROP VIEW IF EXISTS pas_smp.V_WILAYAH_X;

CREATE VIEW pas_smp.V_WILAYAH_X
AS
SELECT  A.ID_PRO AS ID_PRO
,       (
        SELECT  B.NM_PROPINSI AS NM_PROPINSI
        FROM    R_PROPINSI B
        WHERE   (B.ID_PROPINSI = A.ID_PRO)
        ) AS NM_PRO
,       A.ID_KAB AS ID_KAB
,       (
        SELECT  B.NM_KABUPATEN AS NM_KABUPATEN
        FROM    R_KABUPATEN B
        WHERE   (B.ID_KABUPATEN = A.ID_KAB)
        ) AS NM_KAB
,       A.ID_KEC AS ID_KEC
,       (
        SELECT  B.NM_KECAMATAN AS NM_KECAMATAN
        FROM    R_KECAMATAN B
        WHERE   (B.ID_KECAMATAN = A.ID_KEC)
        ) AS NM_KEC
,       A.NPSN AS NPSN
,       A.NM_SEKOLAH AS NM_SEKOLAH
FROM    X_REF_SEKOLAH A
WHERE   (A.JENJANG_SEKOLAH = 3)
AND     (A.KD_JENIS_SEKOLAH = '20');
